### ISSUE TITLE
Admin needs to be able to group users and create schedules

### ISSUE THREAD

**Issue by mrinoldo** [aaronlewis54321/Software_Engineering#19]
- [x] Determine which options admin will have available for scheduling user polling.
- [x] Research best options for menu layout/selection options
- [ ] Consult with product manager about potential use cases for scheduling users

**Comment by youngchan1694** [comment]
-Its better to group users locally so that when we send a "group" a message it actuality we're just sending to the backend database that same timeslot to all the users in that group individually, so that for the database it just looks like multiple users have the same timeslot
-just for the groups, we could have one section for creating/deleting groups then in the section with all the users, there is a drop down bar next to each user in which we can assign them the groups, and finally, in a section that we send messages from, we just choose that group
-i think we should have another issue/backlog for the third part issue because its going to change as the project goes on, plus I am making a use case for the presentation on Thursday
